DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'device_rental') THEN
        CREATE SCHEMA device_rental;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS device_rental."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'device_rental') THEN
            CREATE SCHEMA device_rental;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE TABLE device_rental.roles (
        id uuid NOT NULL,
        name character varying(256) NOT NULL,
        normalized_name character varying(256) NOT NULL,
        concurrency_stamp text,
        CONSTRAINT "PK_roles" PRIMARY KEY (id),
        CONSTRAINT ck_roles_approved_name CHECK (name = btrim(name) AND normalized_name = btrim(normalized_name) AND name <> '' AND name = normalized_name AND normalized_name IN ('USER', 'TEST_ADMIN')),
        CONSTRAINT ck_roles_id_nonzero CHECK (id <> '00000000-0000-0000-0000-000000000000'::uuid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE TABLE device_rental.users (
        id uuid NOT NULL,
        real_name character varying(200) NOT NULL,
        is_active boolean NOT NULL DEFAULT TRUE,
        authorization_version bigint NOT NULL DEFAULT 1,
        email_verified_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        user_name character varying(256) NOT NULL,
        normalized_user_name character varying(256) NOT NULL,
        email character varying(256) NOT NULL,
        normalized_email character varying(256) NOT NULL,
        email_confirmed boolean NOT NULL,
        password_hash text,
        security_stamp text,
        concurrency_stamp text,
        phone_number text,
        phone_number_confirmed boolean NOT NULL,
        two_factor_enabled boolean NOT NULL,
        lockout_end timestamp with time zone,
        lockout_enabled boolean NOT NULL,
        access_failed_count integer NOT NULL,
        CONSTRAINT "PK_users" PRIMARY KEY (id),
        CONSTRAINT ck_users_access_failed_count_nonnegative CHECK (access_failed_count >= 0),
        CONSTRAINT ck_users_authorization_version_positive CHECK (authorization_version > 0),
        CONSTRAINT ck_users_email_identity CHECK (email = btrim(email) AND user_name = btrim(user_name) AND normalized_email = btrim(normalized_email) AND normalized_user_name = btrim(normalized_user_name) AND email <> '' AND normalized_email <> '' AND user_name = email AND normalized_user_name = normalized_email),
        CONSTRAINT ck_users_email_verification_tuple CHECK ((email_confirmed AND email_verified_at IS NOT NULL) OR (NOT email_confirmed AND email_verified_at IS NULL)),
        CONSTRAINT ck_users_id_nonzero CHECK (id <> '00000000-0000-0000-0000-000000000000'::uuid),
        CONSTRAINT ck_users_real_name_not_blank CHECK (btrim(real_name) <> ''),
        CONSTRAINT ck_users_timestamps CHECK (updated_at >= created_at AND (email_verified_at IS NULL OR email_verified_at >= created_at))
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE TABLE device_rental.role_claims (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        role_id uuid NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT "PK_role_claims" PRIMARY KEY (id),
        CONSTRAINT "FK_role_claims_roles_role_id" FOREIGN KEY (role_id) REFERENCES device_rental.roles (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE TABLE device_rental.user_claims (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id uuid NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT "PK_user_claims" PRIMARY KEY (id),
        CONSTRAINT "FK_user_claims_users_user_id" FOREIGN KEY (user_id) REFERENCES device_rental.users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE TABLE device_rental.user_logins (
        login_provider text NOT NULL,
        provider_key text NOT NULL,
        provider_display_name text,
        user_id uuid NOT NULL,
        CONSTRAINT "PK_user_logins" PRIMARY KEY (login_provider, provider_key),
        CONSTRAINT "FK_user_logins_users_user_id" FOREIGN KEY (user_id) REFERENCES device_rental.users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE TABLE device_rental.user_roles (
        user_id uuid NOT NULL,
        role_id uuid NOT NULL,
        CONSTRAINT "PK_user_roles" PRIMARY KEY (user_id, role_id),
        CONSTRAINT "FK_user_roles_roles_role_id" FOREIGN KEY (role_id) REFERENCES device_rental.roles (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_user_roles_users_user_id" FOREIGN KEY (user_id) REFERENCES device_rental.users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE TABLE device_rental.user_tokens (
        user_id uuid NOT NULL,
        login_provider text NOT NULL,
        name text NOT NULL,
        value text,
        CONSTRAINT "PK_user_tokens" PRIMARY KEY (user_id, login_provider, name),
        CONSTRAINT "FK_user_tokens_users_user_id" FOREIGN KEY (user_id) REFERENCES device_rental.users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE INDEX "IX_role_claims_role_id" ON device_rental.role_claims (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE UNIQUE INDEX ux_roles_normalized_name ON device_rental.roles (normalized_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE INDEX "IX_user_claims_user_id" ON device_rental.user_claims (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE INDEX "IX_user_logins_user_id" ON device_rental.user_logins (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE INDEX "IX_user_roles_role_id" ON device_rental.user_roles (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE UNIQUE INDEX ux_users_normalized_email ON device_rental.users (normalized_email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    CREATE UNIQUE INDEX ux_users_normalized_user_name ON device_rental.users (normalized_user_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110049_IdentityAndAccessPolicy') THEN
    INSERT INTO device_rental."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260901110049_IdentityAndAccessPolicy', '10.0.11');
    END IF;
END $EF$;
COMMIT;
START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110222_AuditAndOutbox') THEN
    CREATE TABLE device_rental.audit_events (
        event_id uuid NOT NULL,
        actor_kind character varying(24) NOT NULL,
        actor_user_id uuid,
        external_actor_identifier character varying(256),
        event_type character varying(128) NOT NULL,
        subject_type character varying(128) NOT NULL,
        subject_id character varying(256) NOT NULL,
        changed_fields_json jsonb NOT NULL,
        reason character varying(1000),
        correlation_id character varying(128) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_audit_events" PRIMARY KEY (event_id),
        CONSTRAINT ck_audit_events_actor_kind CHECK (actor_kind IN ('USER', 'SYSTEM', 'OPERATIONS')),
        CONSTRAINT ck_audit_events_actor_tuple CHECK ((actor_kind = 'USER' AND actor_user_id IS NOT NULL AND external_actor_identifier IS NULL) OR (actor_kind = 'SYSTEM' AND actor_user_id IS NULL AND external_actor_identifier IS NULL) OR (actor_kind = 'OPERATIONS' AND actor_user_id IS NULL AND external_actor_identifier IS NOT NULL AND btrim(external_actor_identifier) <> '')),
        CONSTRAINT ck_audit_events_changed_fields_shape CHECK (jsonb_typeof(changed_fields_json) = 'object' AND changed_fields_json ? 'before' AND jsonb_typeof(changed_fields_json -> 'before') = 'object' AND changed_fields_json ? 'after' AND jsonb_typeof(changed_fields_json -> 'after') = 'object' AND changed_fields_json - 'before' - 'after' = '{}'::jsonb),
        CONSTRAINT ck_audit_events_id_nonzero CHECK (event_id <> '00000000-0000-0000-0000-000000000000'::uuid),
        CONSTRAINT ck_audit_events_reason_not_blank CHECK (reason IS NULL OR btrim(reason) <> ''),
        CONSTRAINT ck_audit_events_required_text CHECK (btrim(event_type) <> '' AND btrim(subject_type) <> '' AND btrim(subject_id) <> '' AND btrim(correlation_id) <> ''),
        CONSTRAINT "FK_audit_events_users_actor_user_id" FOREIGN KEY (actor_user_id) REFERENCES device_rental.users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110222_AuditAndOutbox') THEN
    CREATE TABLE device_rental.outbox_messages (
        event_id uuid NOT NULL,
        dedupe_key character varying(256) NOT NULL,
        event_type character varying(128) NOT NULL,
        aggregate_type character varying(128) NOT NULL,
        aggregate_id character varying(256) NOT NULL,
        aggregate_version bigint NOT NULL,
        correlation_id character varying(128) NOT NULL,
        payload_schema_version integer,
        payload_key_version character varying(128),
        payload_ciphertext bytea,
        created_at timestamp with time zone NOT NULL,
        available_at timestamp with time zone NOT NULL,
        status character varying(32) NOT NULL,
        attempts integer NOT NULL DEFAULT 0,
        lease_id uuid,
        locked_by character varying(256),
        locked_until timestamp with time zone,
        sending_started_at timestamp with time zone,
        processed_at timestamp with time zone,
        canceled_at timestamp with time zone,
        failed_at timestamp with time zone,
        last_error character varying(2000),
        payload_purged_at timestamp with time zone,
        CONSTRAINT "PK_outbox_messages" PRIMARY KEY (event_id),
        CONSTRAINT ck_outbox_messages_id_nonzero CHECK (event_id <> '00000000-0000-0000-0000-000000000000'::uuid),
        CONSTRAINT ck_outbox_messages_lease_tuple CHECK ((lease_id IS NULL AND locked_by IS NULL AND locked_until IS NULL) OR (lease_id IS NOT NULL AND lease_id <> '00000000-0000-0000-0000-000000000000'::uuid AND locked_by IS NOT NULL AND btrim(locked_by) <> '' AND locked_until IS NOT NULL)),
        CONSTRAINT ck_outbox_messages_payload_retention CHECK ((status IN ('PENDING', 'CLAIMED', 'SENDING') AND payload_schema_version IS NOT NULL AND payload_key_version IS NOT NULL AND payload_ciphertext IS NOT NULL AND payload_purged_at IS NULL) OR (status IN ('PROCESSED', 'DEAD_LETTER', 'REVIEW_REQUIRED', 'CANCELLED') AND ((payload_schema_version IS NOT NULL AND payload_key_version IS NOT NULL AND payload_ciphertext IS NOT NULL AND payload_purged_at IS NULL) OR (payload_schema_version IS NULL AND payload_key_version IS NULL AND payload_ciphertext IS NULL AND payload_purged_at IS NOT NULL)))),
        CONSTRAINT ck_outbox_messages_payload_tuple CHECK ((payload_schema_version IS NULL AND payload_key_version IS NULL AND payload_ciphertext IS NULL) OR (payload_schema_version > 0 AND payload_key_version IS NOT NULL AND btrim(payload_key_version) <> '' AND payload_ciphertext IS NOT NULL AND octet_length(payload_ciphertext) > 0)),
        CONSTRAINT ck_outbox_messages_required_values CHECK (btrim(dedupe_key) <> '' AND btrim(event_type) <> '' AND btrim(aggregate_type) <> '' AND btrim(aggregate_id) <> '' AND aggregate_version > 0 AND btrim(correlation_id) <> ''),
        CONSTRAINT ck_outbox_messages_state_tuple CHECK ((status = 'PENDING' AND lease_id IS NULL AND locked_by IS NULL AND locked_until IS NULL AND sending_started_at IS NULL AND processed_at IS NULL AND canceled_at IS NULL AND failed_at IS NULL AND ((attempts = 0 AND last_error IS NULL) OR (attempts > 0 AND last_error IS NOT NULL AND btrim(last_error) <> ''))) OR (status = 'CLAIMED' AND lease_id IS NOT NULL AND locked_by IS NOT NULL AND locked_until IS NOT NULL AND sending_started_at IS NULL AND processed_at IS NULL AND canceled_at IS NULL AND failed_at IS NULL AND ((attempts = 0 AND last_error IS NULL) OR (attempts > 0 AND last_error IS NOT NULL AND btrim(last_error) <> ''))) OR (status = 'SENDING' AND lease_id IS NOT NULL AND locked_by IS NOT NULL AND locked_until IS NOT NULL AND attempts > 0 AND sending_started_at IS NOT NULL AND processed_at IS NULL AND canceled_at IS NULL AND failed_at IS NULL AND last_error IS NULL) OR (status = 'PROCESSED' AND lease_id IS NOT NULL AND locked_by IS NOT NULL AND locked_until IS NOT NULL AND attempts > 0 AND sending_started_at IS NOT NULL AND processed_at IS NOT NULL AND canceled_at IS NULL AND failed_at IS NULL AND last_error IS NULL) OR (status IN ('DEAD_LETTER', 'REVIEW_REQUIRED') AND lease_id IS NOT NULL AND locked_by IS NOT NULL AND locked_until IS NOT NULL AND attempts > 0 AND sending_started_at IS NOT NULL AND processed_at IS NULL AND canceled_at IS NULL AND failed_at IS NOT NULL AND last_error IS NOT NULL AND btrim(last_error) <> '') OR (status = 'CANCELLED' AND sending_started_at IS NULL AND processed_at IS NULL AND canceled_at IS NOT NULL AND failed_at IS NULL AND last_error IS NULL AND (lease_id IS NULL AND locked_by IS NULL AND locked_until IS NULL OR (lease_id IS NOT NULL AND locked_by IS NOT NULL AND locked_until IS NOT NULL)))),
        CONSTRAINT ck_outbox_messages_status CHECK (status IN ('PENDING', 'CLAIMED', 'SENDING', 'PROCESSED', 'DEAD_LETTER', 'REVIEW_REQUIRED', 'CANCELLED')),
        CONSTRAINT ck_outbox_messages_time_order CHECK (available_at >= created_at AND attempts >= 0 AND (locked_until IS NULL OR locked_until > created_at) AND (sending_started_at IS NULL OR (sending_started_at >= available_at AND sending_started_at < locked_until)) AND (processed_at IS NULL OR processed_at >= sending_started_at) AND (failed_at IS NULL OR failed_at >= sending_started_at) AND (canceled_at IS NULL OR canceled_at >= created_at) AND (payload_purged_at IS NULL OR payload_purged_at >= COALESCE(processed_at, canceled_at, failed_at)))
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110222_AuditAndOutbox') THEN
    CREATE INDEX ix_audit_events_actor_user_id_created_at ON device_rental.audit_events (actor_user_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110222_AuditAndOutbox') THEN
    CREATE INDEX ix_audit_events_correlation_id ON device_rental.audit_events (correlation_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110222_AuditAndOutbox') THEN
    CREATE INDEX ix_audit_events_created_at_event_id ON device_rental.audit_events (created_at, event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110222_AuditAndOutbox') THEN
    CREATE INDEX ix_audit_events_event_type_created_at ON device_rental.audit_events (event_type, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110222_AuditAndOutbox') THEN
    CREATE INDEX ix_audit_events_subject_created_at ON device_rental.audit_events (subject_type, subject_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110222_AuditAndOutbox') THEN
    CREATE INDEX ix_outbox_messages_aggregate_version ON device_rental.outbox_messages (aggregate_type, aggregate_id, aggregate_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110222_AuditAndOutbox') THEN
    CREATE INDEX ix_outbox_messages_correlation_id ON device_rental.outbox_messages (correlation_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110222_AuditAndOutbox') THEN
    CREATE UNIQUE INDEX ux_outbox_messages_dedupe_key ON device_rental.outbox_messages (dedupe_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM device_rental."__EFMigrationsHistory" WHERE "MigrationId" = '20260901110222_AuditAndOutbox') THEN
    INSERT INTO device_rental."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260901110222_AuditAndOutbox', '10.0.11');
    END IF;
END $EF$;
COMMIT;
