// <auto-generated />
using System;
using DeviceRental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeviceRental.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DeviceRentalDbContext))]
    [Migration("20260902095703_AuditAndOutbox")]
    partial class AuditAndOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("device_rental")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeviceRental.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<long>("AuthorizationVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("authorization_version");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("real_name");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_user_name");

                    b.ToTable("users", "device_rental", t =>
                        {
                            t.HasCheckConstraint("ck_users_access_failed_count_nonnegative", "access_failed_count >= 0");

                            t.HasCheckConstraint("ck_users_authorization_version_positive", "authorization_version > 0");

                            t.HasCheckConstraint("ck_users_email_identity", "email = btrim(email) AND user_name = btrim(user_name) AND normalized_email = btrim(normalized_email) AND normalized_user_name = btrim(normalized_user_name) AND email <> '' AND normalized_email <> '' AND user_name = email AND normalized_user_name = normalized_email");

                            t.HasCheckConstraint("ck_users_email_verification_tuple", "(email_confirmed AND email_verified_at IS NOT NULL) OR (NOT email_confirmed AND email_verified_at IS NULL)");

                            t.HasCheckConstraint("ck_users_id_nonzero", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_users_real_name_not_blank", "btrim(real_name) <> ''");

                            t.HasCheckConstraint("ck_users_timestamps", "updated_at >= created_at AND (email_verified_at IS NULL OR email_verified_at >= created_at)");
                        });
                });

            modelBuilder.Entity("DeviceRental.Infrastructure.Persistence.Records.AuditEventRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("actor_kind");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("ChangedFieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_fields_json");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<string>("ExternalActorIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_actor_identifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("subject_type");

                    b.HasKey("EventId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_events_correlation_id");

                    b.HasIndex("ActorUserId", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_actor_user_id_created_at");

                    b.HasIndex("CreatedAt", "EventId")
                        .HasDatabaseName("ix_audit_events_created_at_event_id");

                    b.HasIndex("EventType", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_event_type_created_at");

                    b.HasIndex("SubjectType", "SubjectId", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_subject_created_at");

                    b.ToTable("audit_events", "device_rental", t =>
                        {
                            t.HasCheckConstraint("ck_audit_events_actor_kind", "actor_kind IN ('USER', 'SYSTEM', 'OPERATIONS')");

                            t.HasCheckConstraint("ck_audit_events_actor_tuple", "(actor_kind = 'USER' AND actor_user_id IS NOT NULL AND external_actor_identifier IS NULL) OR (actor_kind = 'SYSTEM' AND actor_user_id IS NULL AND external_actor_identifier IS NULL) OR (actor_kind = 'OPERATIONS' AND actor_user_id IS NULL AND external_actor_identifier IS NOT NULL AND btrim(external_actor_identifier) <> '')");

                            t.HasCheckConstraint("ck_audit_events_changed_fields_shape", "jsonb_typeof(changed_fields_json) = 'object' AND changed_fields_json ? 'before' AND jsonb_typeof(changed_fields_json -> 'before') = 'object' AND changed_fields_json ? 'after' AND jsonb_typeof(changed_fields_json -> 'after') = 'object' AND changed_fields_json - 'before' - 'after' = '{}'::jsonb");

                            t.HasCheckConstraint("ck_audit_events_id_nonzero", "event_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_audit_events_reason_not_blank", "reason IS NULL OR btrim(reason) <> ''");

                            t.HasCheckConstraint("ck_audit_events_required_text", "btrim(event_type) <> '' AND btrim(subject_type) <> '' AND btrim(subject_id) <> '' AND btrim(correlation_id) <> ''");
                        });
                });

            modelBuilder.Entity("DeviceRental.Infrastructure.Persistence.Records.DeviceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("asset_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("ManualState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("manual_state");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_name");

                    b.Property<string>("TemporaryUnavailableReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("temporary_unavailable_reason");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AssetNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_devices_asset_number");

                    b.HasIndex("ManualState")
                        .HasDatabaseName("ix_devices_manual_state");

                    b.HasIndex("IsArchived", "Tier")
                        .HasDatabaseName("ix_devices_archive_tier");

                    b.ToTable("devices", "device_rental", t =>
                        {
                            t.HasCheckConstraint("ck_devices_id_nonzero", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_devices_manual_state", "manual_state IN ('NORMAL', 'TEMPORARILY_DISABLED')");

                            t.HasCheckConstraint("ck_devices_required_text", "btrim(asset_number) <> '' AND btrim(model_name) <> ''");

                            t.HasCheckConstraint("ck_devices_tier", "tier IN ('LOW', 'MID', 'HIGH')");

                            t.HasCheckConstraint("ck_devices_timestamps", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_devices_unavailable_reason", "(manual_state = 'NORMAL' AND temporary_unavailable_reason IS NULL) OR (manual_state = 'TEMPORARILY_DISABLED' AND temporary_unavailable_reason IS NOT NULL AND btrim(temporary_unavailable_reason) <> '')");

                            t.HasCheckConstraint("ck_devices_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("DeviceRental.Infrastructure.Persistence.Records.LoanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BorrowedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("borrowed_at");

                    b.Property<Guid>("BorrowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("borrower_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<Guid>("PolicyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_version_id");

                    b.Property<string>("ReturnKind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("return_kind");

                    b.Property<string>("ReturnReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("return_reason");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_at");

                    b.Property<Guid?>("ReturnedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("returned_by_user_id");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ux_loans_open_device")
                        .HasFilter("returned_at IS NULL");

                    b.HasIndex("ReturnedByUserId");

                    b.HasIndex("BorrowerId", "BorrowedAt")
                        .HasDatabaseName("ix_loans_borrower_borrowed_at");

                    b.HasIndex("DueAt", "ReturnedAt")
                        .HasDatabaseName("ix_loans_due_returned");

                    b.ToTable("loans", "device_rental", t =>
                        {
                            t.HasCheckConstraint("ck_loans_id_nonzero", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_loans_parties_nonzero", "device_id <> '00000000-0000-0000-0000-000000000000'::uuid AND borrower_id <> '00000000-0000-0000-0000-000000000000'::uuid AND policy_version_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_loans_return_tuple", "(returned_at IS NULL AND returned_by_user_id IS NULL AND return_kind IS NULL AND return_reason IS NULL) OR (returned_at IS NOT NULL AND returned_by_user_id IS NOT NULL AND returned_by_user_id <> '00000000-0000-0000-0000-000000000000'::uuid AND return_kind IN ('SELF', 'FORCED') AND ((return_kind = 'SELF' AND returned_by_user_id = borrower_id AND return_reason IS NULL) OR (return_kind = 'FORCED' AND return_reason IS NOT NULL AND btrim(return_reason) <> '')))");

                            t.HasCheckConstraint("ck_loans_time_order", "due_at > borrowed_at AND (returned_at IS NULL OR returned_at >= borrowed_at)");

                            t.HasCheckConstraint("ck_loans_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("DeviceRental.Infrastructure.Persistence.Records.OutboxMessageRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceled_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<byte[]>("PayloadCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("payload_ciphertext");

                    b.Property<string>("PayloadKeyVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload_key_version");

                    b.Property<DateTimeOffset?>("PayloadPurgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payload_purged_at");

                    b.Property<int?>("PayloadSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("payload_schema_version");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset?>("SendingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sending_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("EventId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_outbox_messages_correlation_id");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_messages_dedupe_key");

                    b.HasIndex("AggregateType", "AggregateId", "AggregateVersion")
                        .HasDatabaseName("ix_outbox_messages_aggregate_version");

                    b.ToTable("outbox_messages", "device_rental", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_id_nonzero", "event_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_outbox_messages_lease_tuple", "(lease_id IS NULL AND locked_by IS NULL AND locked_until IS NULL) OR (lease_id IS NOT NULL AND lease_id <> '00000000-0000-0000-0000-000000000000'::uuid AND locked_by IS NOT NULL AND btrim(locked_by) <> '' AND locked_until IS NOT NULL)");

                            t.HasCheckConstraint("ck_outbox_messages_payload_retention", "(status IN ('PENDING', 'CLAIMED', 'SENDING') AND payload_schema_version IS NOT NULL AND payload_key_version IS NOT NULL AND payload_ciphertext IS NOT NULL AND payload_purged_at IS NULL) OR (status IN ('PROCESSED', 'DEAD_LETTER', 'REVIEW_REQUIRED', 'CANCELLED') AND ((payload_schema_version IS NOT NULL AND payload_key_version IS NOT NULL AND payload_ciphertext IS NOT NULL AND payload_purged_at IS NULL) OR (payload_schema_version IS NULL AND payload_key_version IS NULL AND payload_ciphertext IS NULL AND payload_purged_at IS NOT NULL)))");

                            t.HasCheckConstraint("ck_outbox_messages_payload_tuple", "(payload_schema_version IS NULL AND payload_key_version IS NULL AND payload_ciphertext IS NULL) OR (payload_schema_version > 0 AND payload_key_version IS NOT NULL AND btrim(payload_key_version) <> '' AND payload_ciphertext IS NOT NULL AND octet_length(payload_ciphertext) > 0)");

                            t.HasCheckConstraint("ck_outbox_messages_required_values", "btrim(dedupe_key) <> '' AND btrim(event_type) <> '' AND btrim(aggregate_type) <> '' AND btrim(aggregate_id) <> '' AND aggregate_version > 0 AND btrim(correlation_id) <> ''");

                            t.HasCheckConstraint("ck_outbox_messages_state_tuple", "(status = 'PENDING' AND lease_id IS NULL AND locked_by IS NULL AND locked_until IS NULL AND sending_started_at IS NULL AND processed_at IS NULL AND canceled_at IS NULL AND failed_at IS NULL AND ((attempts = 0 AND last_error IS NULL) OR (attempts > 0 AND last_error IS NOT NULL AND btrim(last_error) <> ''))) OR (status = 'CLAIMED' AND lease_id IS NOT NULL AND locked_by IS NOT NULL AND locked_until IS NOT NULL AND sending_started_at IS NULL AND processed_at IS NULL AND canceled_at IS NULL AND failed_at IS NULL AND ((attempts = 0 AND last_error IS NULL) OR (attempts > 0 AND last_error IS NOT NULL AND btrim(last_error) <> ''))) OR (status = 'SENDING' AND lease_id IS NOT NULL AND locked_by IS NOT NULL AND locked_until IS NOT NULL AND attempts > 0 AND sending_started_at IS NOT NULL AND processed_at IS NULL AND canceled_at IS NULL AND failed_at IS NULL AND last_error IS NULL) OR (status = 'PROCESSED' AND lease_id IS NOT NULL AND locked_by IS NOT NULL AND locked_until IS NOT NULL AND attempts > 0 AND sending_started_at IS NOT NULL AND processed_at IS NOT NULL AND canceled_at IS NULL AND failed_at IS NULL AND last_error IS NULL) OR (status IN ('DEAD_LETTER', 'REVIEW_REQUIRED') AND lease_id IS NOT NULL AND locked_by IS NOT NULL AND locked_until IS NOT NULL AND attempts > 0 AND sending_started_at IS NOT NULL AND processed_at IS NULL AND canceled_at IS NULL AND failed_at IS NOT NULL AND last_error IS NOT NULL AND btrim(last_error) <> '') OR (status = 'CANCELLED' AND sending_started_at IS NULL AND processed_at IS NULL AND canceled_at IS NOT NULL AND failed_at IS NULL AND last_error IS NULL AND (lease_id IS NULL AND locked_by IS NULL AND locked_until IS NULL OR (lease_id IS NOT NULL AND locked_by IS NOT NULL AND locked_until IS NOT NULL)))");

                            t.HasCheckConstraint("ck_outbox_messages_status", "status IN ('PENDING', 'CLAIMED', 'SENDING', 'PROCESSED', 'DEAD_LETTER', 'REVIEW_REQUIRED', 'CANCELLED')");

                            t.HasCheckConstraint("ck_outbox_messages_time_order", "available_at >= created_at AND attempts >= 0 AND (locked_until IS NULL OR locked_until > created_at) AND (sending_started_at IS NULL OR (sending_started_at >= available_at AND sending_started_at < locked_until)) AND (processed_at IS NULL OR processed_at >= sending_started_at) AND (failed_at IS NULL OR failed_at >= sending_started_at) AND (canceled_at IS NULL OR canceled_at >= created_at) AND (payload_purged_at IS NULL OR payload_purged_at >= COALESCE(processed_at, canceled_at, failed_at))");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_normalized_name");

                    b.ToTable("roles", "device_rental", t =>
                        {
                            t.HasCheckConstraint("ck_roles_approved_name", "name = btrim(name) AND normalized_name = btrim(normalized_name) AND name <> '' AND name = normalized_name AND normalized_name IN ('USER', 'TEST_ADMIN')");

                            t.HasCheckConstraint("ck_roles_id_nonzero", "id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", "device_rental");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", "device_rental");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", "device_rental");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "device_rental");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", "device_rental");
                });

            modelBuilder.Entity("DeviceRental.Infrastructure.Persistence.Records.AuditEventRecord", b =>
                {
                    b.HasOne("DeviceRental.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DeviceRental.Infrastructure.Persistence.Records.LoanRecord", b =>
                {
                    b.HasOne("DeviceRental.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeviceRental.Infrastructure.Persistence.Records.DeviceRecord", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeviceRental.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReturnedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DeviceRental.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DeviceRental.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeviceRental.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DeviceRental.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
